### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [BGR360/LuigiSimulator#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by BGR360** [comment]
Hi. I have not specified a license because I never thought anyone would be interested in this project. Could you please tell me what you would like to do with it?

**Comment by BGR360** [comment]
Accidentally closed, whoops

**Comment by suprafun** [comment]
As a learning resource, how I might write a simulator. I have not actually looked at your project in detail. So I don't know what I might learn from it. But I am pretty much new to Unity3D so I am sure there are something to learn :)

**Comment by BGR360** [comment]
Oh absolutely feel free to learn from it! Just let me know if you ever try to sell something or claim the code as your own :)

**Comment by BGR360** [comment]
Also, I'm kinda surprised at how you came across this project. Could you let me me know what led you here? I'm very curious

**Comment by suprafun** [comment]
Searching for Unity samples under words like " simulation " , " simulator " etc.

Will let you know :)
